CREATE TABLE active (
	today char(4) DEFAULT 'TODAY' NOT NULL,
	invoice char(20) DEFAULT 'INVOICE' NOT NULL,
	description char(10) DEFAULT 'DESCRIPTION' NOT NULL,
	amount char(7) DEFAULT 'AMOUNT' NOT NULL,
	custid char(30) DEFAULT 'CUSTID' NOT NULL,
	method char(16) DEFAULT 'METHOD' NOT NULL,
	type char(2) DEFAULT 'TYPE' NOT NULL,
	cardnum char(20) DEFAULT 'CARDNUM' NOT NULL,
	expdate char(4) DEFAULT 'EXPDATE' NOT NULL,
	authcode char(12) DEFAULT 'AUTHCODE' NOT NULL,
	acctno char(20) DEFAULT 'ACCTNO' NOT NULL,
	abacode char(9) DEFAULT 'ABACODE' NOT NULL,
	bankname char(24) DEFAULT 'BANKNAME' NOT NULL,
	name char(24) DEFAULT 'NAME' NOT NULL,
	address char(30) DEFAULT 'ADDRESS' NOT NULL,
	city char(24) DEFAULT 'CITY' NOT NULL,
	state char(12) DEFAULT 'STATE' NOT NULL,
	zip char(12) DEFAULT 'ZIP' NOT NULL,
	country char(24) DEFAULT 'COUNTRY' NOT NULL,
	phone char(12) DEFAULT 'PHONE' NOT NULL,
	fax char(12) DEFAULT 'FAX' NOT NULL,
	email char(30) DEFAULT 'EMAIL' NOT NULL,
	membership char(6) DEFAULT 'MEMBERSHIP' NOT NULL,
	expire char(6) DEFAULT 'EXPIRE' NOT NULL,
	cycle char(6) DEFAULT 'CYCLE' NOT NULL,
	status char(12) DEFAULT 'STATUS' NOT NULL,
	username char(50) DEFAULT 'USERNAME' NOT NULL,
	password char(12) DEFAULT 'PASSWORD' NOT NULL,
	binterval char(3) DEFAULT 'BINTERVAL' NOT NULL,
	delay char(3) DEFAULT 'DELAY' NOT NULL,
	rebillattempt char(3) DEFAULT 'DELAY' NOT NULL,
	PRIMARY KEY(username)
);

CREATE TABLE expired (
	today char(4) DEFAULT 'TODAY' NOT NULL,
	invoice char(20) DEFAULT 'INVOICE' NOT NULL,
	description char(10) DEFAULT 'DESCRIPTION' NOT NULL,
	amount char(7) DEFAULT 'AMOUNT' NOT NULL,
	custid char(30) DEFAULT 'CUSTID' NOT NULL,
	method char(16) DEFAULT 'METHOD' NOT NULL,
	type char(2) DEFAULT 'TYPE' NOT NULL,
	cardnum char(20) DEFAULT 'CARDNUM' NOT NULL,
	expdate char(4) DEFAULT 'EXPDATE' NOT NULL,
	authcode char(12) DEFAULT 'AUTHCODE' NOT NULL,
	acctno char(20) DEFAULT 'ACCTNO' NOT NULL,
	abacode char(9) DEFAULT 'ABACODE' NOT NULL,
	bankname char(24) DEFAULT 'BANKNAME' NOT NULL,
	name char(24) DEFAULT 'NAME' NOT NULL,
	address char(30) DEFAULT 'ADDRESS' NOT NULL,
	city char(24) DEFAULT 'CITY' NOT NULL,
	state char(12) DEFAULT 'STATE' NOT NULL,
	zip char(12) DEFAULT 'ZIP' NOT NULL,
	country char(24) DEFAULT 'COUNTRY' NOT NULL,
	phone char(12) DEFAULT 'PHONE' NOT NULL,
	fax char(12) DEFAULT 'FAX' NOT NULL,
	email char(30) DEFAULT 'EMAIL' NOT NULL,
	membership char(6) DEFAULT 'MEMBERSHIP' NOT NULL,
	expire char(6) DEFAULT 'EXPIRE' NOT NULL,
	cycle char(6) DEFAULT 'CYCLE' NOT NULL,
	status char(12) DEFAULT 'STATUS' NOT NULL,
	username char(50) DEFAULT 'USERNAME' NOT NULL,
	password char(12) DEFAULT 'PASSWORD' NOT NULL,
	binterval char(3) DEFAULT 'BINTERVAL' NOT NULL,
	delay char(3) DEFAULT 'DELAY' NOT NULL,
	PRIMARY KEY(username)
);

CREATE TABLE billinglog (
	today char(4) DEFAULT 'TODAY' NOT NULL,
	invoice char(20) DEFAULT 'INVOICE' NOT NULL,
	description char(10) DEFAULT 'DESCRIPTION' NOT NULL,
	amount char(7) DEFAULT 'AMOUNT' NOT NULL,
	custid char(30) DEFAULT 'CUSTID' NOT NULL,
	method char(16) DEFAULT 'METHOD' NOT NULL,
	type char(2) DEFAULT 'TYPE' NOT NULL,
	cardnum char(20) DEFAULT 'CARDNUM' NOT NULL,
	expdate char(4) DEFAULT 'EXPDATE' NOT NULL,
	authcode char(12) DEFAULT 'AUTHCODE' NOT NULL,
	acctno char(20) DEFAULT 'ACCTNO' NOT NULL,
	abacode char(9) DEFAULT 'ABACODE' NOT NULL,
	bankname char(24) DEFAULT 'BANKNAME' NOT NULL,
	name char(24) DEFAULT 'NAME' NOT NULL,
	address char(30) DEFAULT 'ADDRESS' NOT NULL,
	city char(24) DEFAULT 'CITY' NOT NULL,
	state char(12) DEFAULT 'STATE' NOT NULL,
	zip char(12) DEFAULT 'ZIP' NOT NULL,
	country char(24) DEFAULT 'COUNTRY' NOT NULL,
	phone char(12) DEFAULT 'PHONE' NOT NULL,
	fax char(12) DEFAULT 'FAX' NOT NULL,
	email char(30) DEFAULT 'EMAIL' NOT NULL,
	membership char(6) DEFAULT 'MEMBERSHIP' NOT NULL,
	expire char(6) DEFAULT 'EXPIRE' NOT NULL,
	cycle char(6) DEFAULT 'CYCLE' NOT NULL,
	status char(12) DEFAULT 'STATUS' NOT NULL,
	username char(50) DEFAULT 'USERNAME' NOT NULL,
	password char(12) DEFAULT 'PASSWORD' NOT NULL,
	binterval char(3) DEFAULT 'BINTERVAL' NOT NULL,
	delay char(3) DEFAULT 'DELAY' NOT NULL,
	PRIMARY KEY(invoice)
);

CREATE TABLE negative (
	cardnum char(20) DEFAULT 'CARDNUM' NOT NULL,
	acctno char(20) DEFAULT 'ACCTNO' NOT NULL,
	PRIMARY KEY(cardnum,acctno)
);

CREATE TABLE userpass (
	username char(100) DEFAULT 'USERNAME' NOT NULL,
	crypted char(100) DEFAULT 'PASSWORD' NOT NULL,
	PRIMARY KEY(username)
);